### ISSUE TITLE
Storybook docs height with Firefox

### ISSUE THREAD

**Issue by HugoPerard** [BearStudio/start-ui-web#179] opened 2022-02-25 14:24 UTC
**The problem** : 
When I'm on Firefox, Storybooks docs height looks minimal. In comparison at Chrome, docs height fit the content.

With Firefox : 
![Capture d’écran 2022-02-25 à 15 02 03](https://user-images.githubusercontent.com/48803115/155731355-e6a8fccc-22b8-44ff-95ee-c2b248d79a7b.png)

With Chrome :
![Capture d’écran 2022-02-25 à 15 02 29](https://user-images.githubusercontent.com/48803115/155731373-067ea7de-562b-4a80-8c86-27dab3910706.png)

**Comment by HugoPerard** [comment] 2022-03-04 23:49
I don't have any extensions, and my cache is clear 😞

**Comment by Jessy-BAER** [comment] 2022-05-27 17:00
Same for me 

![image](https://user-images.githubusercontent.com/7570753/170745669-8f852fcc-0e2b-403d-bc62-115cf615a4e7.png)

**Comment by yoannfleurydev** [comment] 2022-05-27 22:58
> This line in [preview.js](https://github.com/BearStudio/start-ui-web/blob/3b0f48d6fde760cd68a00638a64c41af9ca906df/.storybook/preview.js#L84) is not applied on firefox

I did reproduce, but I don't think padding is the cause of the problem. I agree that DevTools are saying so, but we can clearly see the padding by inspecting the computed tab. (Also, on localhost, DevTools are not saying padding have problems)

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/3920615/170798396-1c258d86-3f24-4b07-ad84-8234a5132cd7.png">

**Comment by yoannfleurydev** [comment] 2023-05-04 08:49
I did test that in production (https://demo.start-ui.com/storybook), it looks like it has been fixed, I'm closing this issue. Feel free to reopen if it happens again.

**Closed by yoannfleurydev** 2023-05-04 08:49 UTC
Labels: bug:third-party
