### ISSUE TITLE
Strange behavior on the eye button on the password field

### ISSUE THREAD

**Issue by DecampsRenan** [BearStudio/start-ui-web#363] opened 2023-05-26 14:17 UTC
When I click on the eye there is a strange behavior (it seems to react as if I double clicked on it)

https://github.com/BearStudio/start-ui-web/assets/7521065/e4fe6877-da75-4ace-815e-c29a89c2b9fc

Need to be checked on another device than mine

**Comment by Dhananjay-12** [comment] 2023-05-26 16:21
<img width="343" alt="eye issue" src="https://github.com/BearStudio/start-ui-web/assets/86868676/23b2f1b4-e18e-4e35-82fd-b7e31c230ec0">

##  same here on my device

**Comment by Dhananjay-12** [comment] 2023-05-26 16:22
can I try to fix this (Learning react) ?

**Comment by yoannfleurydev** [comment] 2023-05-26 16:25
> can I try to fix this (Learning react) ?

Hey sure, I assigned you to the issue.

**Comment by yoannfleurydev** [comment] 2023-05-26 16:27
@DecampsRenan I can't reproduced on my laptop using https://demo.start-ui.com

**Comment by DecampsRenan** [comment] 2023-05-26 16:43
> @DecampsRenan I can't reproduced on my laptop using [demo.start-ui.com](https://demo.start-ui.com)

I retried too on a mobile device and on my computer, seems working fine :/ didn't know what happened ^^ @Dhananjay-12 I think if you can't reproduce the issue on your local env, we can close this issue (pretty sure it was an issue on my side ^^)

**Comment by Dhananjay-12** [comment] 2023-05-26 16:50
i followed this link ``` https://demo.start-ui.com/ ``` . I can clearly see that eye issue. Should i record that ?

**Comment by yoannfleurydev** [comment] 2023-05-27 09:41
Thanks to you two for your time, I'm closing that issue. We'll re-open if it is a 🚀 Start UI [web] issue and not an environment issue.

**Closed by yoannfleurydev** 2023-05-27 09:41 UTC
Labels: bug, good first issue, components

**Comment by Dhananjay-12** [comment] 2023-05-27 11:19
Hey @yoannfleurydev , is there  anything else I can work on ?

**Comment by yoannfleurydev** [comment] 2023-05-27 13:38
Hey, I think those issues are nice to start to contribute: 

- https://github.com/BearStudio/start-ui-web/issues/279
- https://github.com/BearStudio/start-ui-web/issues/127
- https://github.com/BearStudio/start-ui-web/issues/170
